Abbreviations added

diff --git a/run_once_after_01-setup-fish.sh.tmpl b/run_once_after_01-setup-fish.sh.tmpl
--- a/run_once_after_01-setup-fish.sh.tmpl
+++ b/run_once_after_01-setup-fish.sh.tmpl
@@ -15,9 +15,22 @@ run_fisher_update() {
     fi
 }
 
+# Function to setup fzf
+run_fzf_setup() {
+    if command -v fish &>/dev/null; then
+        echo "Setting up fzf..."
+        fish -c 'fzf_configure_bindings --directory=\co'
+        echo "Fzf setup completed successfully."
+    else
+        echo "Error: Fish shell is not installed or not in PATH." >&2
+        exit 1
+    fi
+}
+
 # Main function
 main() {
     run_fisher_update
+    run_fzf_setup
 }
 
 # Run the main function
